
name: wf-develop-pr

on:
  pull_request:
    branches:
      - develop

jobs:
  develop-pr-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Lint HTML and CSS assets
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"

      - name: Build websitegit 
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"
